### ISSUE TITLE
大傻春，你要干什么！！

### ISSUE THREAD

**Issue by HyperClockUp** [bufferhead-code/nextjs-use-php#6]

**Comment by abcdexx** [comment]
我也不知道我要干什么！

**Comment by StrawDC** [comment]
笑死了md

**Comment by dogeow** [comment]
PHP 是世界上最好的语言！

**Comment by yungifez** [comment]
世了的我我的世了

**Comment by bufferhead-code** [comment]
unfortunately i do not speak chinese. But from what deepl makes me understand you all think it's a very useful and very serious project. Thank you for the support.
