### ISSUE TITLE
You were supposed to fight against evil, not join it!

### ISSUE THREAD

**Issue by ltlaitoff** [bufferhead-code/nextjs-use-php#8]

**Comment by favna** [comment]
https://github.com/bufferhead-code/nextjs-use-php/assets/4019718/fb32bcd1-6742-4ca7-8e82-42cb6287516e

**Comment by Furtsy** [comment]
https://github.com/bufferhead-code/nextjs-use-php/assets/43937364/40f199bf-8292-454b-a567-3edee6c98c18

**Comment by bufferhead-code** [comment]
sorry people, it's too late, i swear i'll join you on the good side next time ✌️
